### PR TITLE
Honor autoconf --prefix arguments

### PR DESCRIPTION
**Pull request by naterini**
For our machines, we generally prefer to put compiled applications in /usr/local. This patch follows the suggestions of GNU (https://www.gnu.org/software/autoconf/manual/autoconf-2.63/html_node/Installation-Directory-Variables.html and https://www.gnu.org/software/automake/manual/html_node/Scripts.html#Scripts) to push the configure settings into the nhc scripts. The main nhc scripts had to be converted to input templates per autoconf convention. 

This patch fixes issue in https://github.com/mej/nhc/issues/62

### CODE REVIEW

**Comment by mej** [comment]
So first, any particular reason you generate the scripts from the `.in` files in the `Makefile` instead of adding them to `AC_OUTPUT()` in `configure.ac` (which is the standard method)?

I'm really torn on this one.  I've kinda been avoiding doing something like this because I have a bit of a visceral reaction to turning all the base scripts into `.in` files, but I also understand the need and motivation to make this work.

One alternative possibility might be to transform the **_installed_** versions of the scripts rather than the sources, possibly with an `automake` `install-exec-hook` rule or something similar.  Would that adequately address your use case?

**Comment by nateucar** [comment]
> So first, any particular reason you generate the scripts from the .in files in the Makefile instead of adding them to AC_OUTPUT() in configure.ac (which is the standard method)?

Yes, I was trying to follow the existing pattern of hardcoding the paths in the final installed script. I think using an environmental variable for these would be much cleaner and could easily swap this pull request to that instead. The downside to using environment could cause behavior to be surprising on a default install though but updating documentation should help with that.

> I'm really torn on this one. I've kinda been avoiding doing something like this because I have a bit of a visceral reaction to turning all the base scripts into .in files

I was following the best practice suggestions from autoconf (https://www.gnu.org/software/automake/manual/html_node/Scripts.html#Scripts). I'm don't actually like this setup either but I assumed you would prefer follow autoconf dev's suggestions.

> One alternative possibility might be to transform the installed versions of the scripts rather than the sources, possibly with an automake install-exec-hook rule or something similar.

Sure. AFAIK appending the ".in" serves as a good warning to any future developers that this file will be modified during install process.

**Comment by eliv** [comment]
Yes, us to. Just Installed nhc 1.4.2 gives weird error messages until I found PATH in the nhc script. Adding /usr/local/bin to find sinfo and scontrol and I can at least start kicking the tires.

**Comment by mej** [comment]
I created a new branch for applying this PR so that we can play around a little with the particulars of how this is implemented before merging into the main branch.  I'm targeting the 1.4.4 release for this since I think it's going to take some trial-and-error to avoid breaking the RPM build (the 1st-class citizen, so to speak) and the GitHub source tree build (what all the kool kids are doing).

**Pull request closed without merging**
